id: ''
title: Kangyur
language: bo
author: ''
volume:
  '001': 68558
sutra:
  68558:
    sutraid: d1
    repeat: J712,J923
    vol: པོད་རྟགས། འདུལ་བ། ༼ཀ༽༼ཁ༽༼ག༽༼ང༽ (1-4)
    page: ༼ཀ༽ 1-1-1a1~1-1-311b2, ༼ཁ༽ 2-1-1a1~2-1-317b2, ༼ག༽ 3-1-1a1~3-1-293b2, ༼ང༽
      4-1-1a1~4-1-302b2
    tname: འདུལ་བ་གཞི།
    wylie: '''dul ba gzhi'
    aname: ''
    sname: བི་ན་ཡ་བསྟུ།
    yname: ''
    roman: vinaya-vastu
    cname: 《根本說一切有部毘奈耶出家事》唐 義淨譯, 《根本說一切有部毘奈耶安居事》唐 義淨譯, 《根本說一切有部毘奈耶隨意事》唐 義淨譯, 《根本說一切有部毘奈耶皮革事》唐
      義淨譯, 《根本說一切有部毘奈耶藥事》唐 義淨譯, 《根本說一切有部毘奈耶羯恥那衣事》唐 義淨譯, 《根本說一切有部毘奈耶破僧事》唐 義淨譯
    cid: T23n1444,T23n1445,T23n1446,T23n1447,T24n1448,T24n1449,T24n1450
    homage: དཀོན་མཆོག་གསུམ་ལ་ཕྱག་འཚལ་ལོ།
    subject: འདུལ་བའི་སྡེ་སྣོད།
    topic: 1
    yana: 1
    school: 0
    chakra: 1
    location: ''
    audience: ''
    author: སངས་རྒྱས་ཤཱཀྱ་ཐུབ་པ།
    requester: ''
    dharma: ''
    purpose: ཐུབ་དབང་ཟླ་བའི་ཞལ་ནས་བྱུང་གྱུར་པ། །གསུང་གི་མེ་ཏོག་ཆར་པ་ཡིད་འོང་རྣམས།
      །ལྟ་བ་ངན་ཟློག་རྙི་བ་མེད་པ་ཡི། །རང་བཞིན་ཡུན་རིང་སྐྱེ་དགུའི་ནང་གནས་ཤོག།
    collect: ''
    bampo: བམ་པོ་བརྒྱ་རྩ་དགུ། ཀ་པར། བམ་པོ་ཉི་ཤུ་བཞི་པའི་བར། ཁ་པར། བམ་པོ་ལྔ་བཅུ་རྩ་བཞི་པའི་བར།
      ག་པར། བམ་པོ་བརྒྱད་བཅུ་རྩ་གཉིས་པའི་བར། ང་པར། བམ་པོ་བརྒྱ་རྩ་དགུ་པའི་བར་རོ། །
    relation: ''
    debate: རབ་ཏུ་འབྱུང་བའི་གཞི་འཆད་པ། སྨན་གྱི་གཞི་འཆད་པ། གོས་ཀྱི་གཞི་འཆད་པ། སྲ་བརྐྱང་གི་གཞི་འཆད་པ།
      ཀཽ་ཤྭམྦཱིའི་གཞི་འཆད་པ། ལས་ཀྱི་གཞི་འཆད་པ། དམར་སེར་ཅན་གྱི་གཞི་འཆད་པ། གང་ཟག་གི་གཞི་འཆད་པ།
      སྤོ་བའི་གཞི་འཆད་པ། གསོ་སྦྱོང་བཞག་པའི་གཞི་འཆད་པ། གནས་མལ་གྱི་གཞི་འཆད་པ། རྩོད་པའི་གཞི་འཆད་པ།
      དགེ་འདུན་དབྱེན་གྱི་གཞི་འཆད་པ།
    translator: ཁ་ཆེའི་མཁན་པོ་སརྦ་ཛྙཱ་དེ་བ་དང་། རྒྱ་གར་གྱི་མཁན་པོ་བིདྱཱ་ཀ་ར་པྲ་བྷ་དང་།
      ཁ་ཆེའི་མཁན་པོ་དྷརྨཱ་ཀ་ར་དང་། ལོ་ཙྪ་བ་བན་དེ་དཔལ་གྱི་ལྷུན་པོས་བསྒྱུར་ཅིང་། རྒྱ་གར་གྱི་མཁན་པོ་བིདྱཱ་ཀ་ར་པྲ་བྷ་དང་།
      ཞུ་ཆེན་གྱི་ལོ་ཙྪ་བ་བན་དེ་དཔལ་བརྩེགས་ཀྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ།
    reviser: ''
    age: 1
